export default {
  auth: {
    stack: 'Auth Stack',
    Password: 'Password',
    SignIn: 'Sign In',
    SignInPassword: 'Sign In Password',
    SignUp: 'Sign Up',
    ForgotPassword: 'Forgot Password',
    FaceId: 'FaceId',
    Splash: 'Splash',
    Welcome: 'Welcome',
  },

  home: {
    stack: 'Auth Stack',
    Password: 'Password',
    SignIn: 'Sign In',
    SignInPassword: 'Sign In Password',
    SignUp: 'Sign Up',
    ForgotPassword: 'Forgot Password',
    FaceId: 'FaceId',
    Splash: 'Splash',
    Welcome: 'Welcome',
  },
  sales: {
    stack: 'Auth Stack',
    Password: 'Password',
    SignIn: 'Sign In',
    SignInPassword: 'Sign In Password',
    SignUp: 'Sign Up',
    ForgotPassword: 'Forgot Password',
    FaceId: 'FaceId',
    Splash: 'Splash',
    Welcome: 'Welcome',
  },
  saved: {
    stack: 'Auth Stack',
    Password: 'Password',
    SignIn: 'Sign In',
    SignInPassword: 'Sign In Password',
    SignUp: 'Sign Up',
    ForgotPassword: 'Forgot Password',
    FaceId: 'FaceId',
    Splash: 'Splash',
    Welcome: 'Welcome',
  },
  settings: {
    stack: 'Auth Stack',
    Password: 'Password',
    SignIn: 'Sign In',
    SignInPassword: 'Sign In Password',
    SignUp: 'Sign Up',
    ForgotPassword: 'Forgot Password',
    FaceId: 'FaceId',
    Splash: 'Splash',
    Welcome: 'Welcome',
  },
  userDetails: {
    stack: 'Auth Stack',
    Password: 'Password',
    SignIn: 'Sign In',
    SignInPassword: 'Sign In Password',
    SignUp: 'Sign Up',
    ForgotPassword: 'Forgot Password',
    FaceId: 'FaceId',
    Splash: 'Splash',
    Welcome: 'Welcome',
  },
  verify: {
    stack: 'Auth Stack',
    Password: 'Password',
    SignIn: 'Sign In',
    SignInPassword: 'Sign In Password',
    SignUp: 'Sign Up',
    ForgotPassword: 'Forgot Password',
    FaceId: 'FaceId',
    Splash: 'Splash',
    Welcome: 'Welcome',
  },
};
