export default {
  id: {key: 'postId', default: 1},
  title: {key: 'title', default: ''},
  about: {key: 'about', default: ''},
  type: {key: 'type', default: ''},
  tags: {key: 'tags', default: {}},
  location: {key: 'location', default: ''},
  startDate: {key: 'startDate', default: ''},
  endDate: {key: 'endDate', default: ''},
  startTime: {key: 'startTime', default: ''},
  endTime: {key: 'endTime', default: ''},
  street: {key: 'street', default: ''},
  streetNumber: {key: 'streetNumber', default: ''},
  zip: {key: 'zip', default: ''},
  city: {key: 'city', default: ''},
  state: {key: 'state', default: ''},
  lat: {key: 'postLat', default: 0},
  long: {key: 'postLong', default: 0},
  calculatedDistance: {key: 'calculatedDistance', default: 0},
};
