-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGv6T0moYmb/3ttp6
9dWZmNTZHALFfESMQVr9mdUFPBygCgYIKoZIzj0DAQehRANCAARZIUb0ua7rSuqL
jqxwdjoajG7K6Q0uSVNoZtrdd4noK7wPm6D3Rk4GCJTHvLnbGJgYC1+quW66Fq1g
WcOHOUNn
-----END PRIVATE KEY-----